services:
  subscription_gateway:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
    build:
      context: ./subscription_gateway
    ports:
      - 8000
    networks:
      - eureka
  discovery_service:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
    build:
      context: ./discovery_service
    ports:
      - 8001
    hostname: discoveryservice
    networks:
      - eureka
  subscription_status_cache:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    build:
      context: ./subscription_status_cache
    ports:
      - 8002
    networks:
      - eureka
      - kafka
  subscription_service:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    build:
      context: ./subscription_service
    ports:
      - 8003
    networks:
      - eureka
      - kafka
  kafka:
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_HOST
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:9092
    image: confluentinc/cp-kafka:7.6.1
    hostname: kafka
    ports:
      - 9092:9092
    networks:
      - kafka
      - zookeeper
  zookeeper:
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ADVERTISED_HOST_NAME=zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    ports:
      - 2181
    networks:
      - zookeeper
networks:
  eureka:
    driver: bridge
  kafka:
    driver: bridge
  zookeeper:
    driver: bridge