services:
  subscription_gateway:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
    build:
      context: ./subscription_gateway
    ports:
      - 8080:8080
    networks:
      - eureka
    depends_on:
      - discovery_service
  discovery_service:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
    build:
      context: ./discovery_service
    ports:
      - 8001
    hostname: discoveryservice
    networks:
      - eureka
  subscription_status_cache:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
      - RABBITMQ_SERVICE_URL=rabbitmq
    build:
      context: ./subscription_status_cache
    ports:
      - 8002
    networks:
      - eureka
      - rabbitmq
    deploy:
      replicas: 3
    depends_on:
      - discovery_service
      - rabbitmq
      - subscription_service
  subscription_service:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
      - RABBITMQ_SERVICE_URL=rabbitmq
    build:
      context: ./subscription_service
    ports:
      - 8003
    networks:
      - eureka
      - rabbitmq
    depends_on:
      - discovery_service
      - rabbitmq
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672 #JMS Port
      - 15672:15672 #Management Port - default user:pass = guest:guest
    networks:
      - rabbitmq
networks:
  eureka:
    driver: bridge
  rabbitmq:
    driver: bridge