services:
  subscription_gateway:
    build:
      context: ./subscription_gateway
    ports:
      - 8000
    networks:
      - eureka
  discovery_service:
    build:
      context: ./discovery_service
    ports:
      - 8001
    networks:
      - eureka
  subscription_status_cache:
    build:
      context: ./subscription_status_cache
    ports:
      - 8002
    networks:
      - eureka
  subscription_server:
    build:
      context: ./subscription_server
    ports:
      - 8003
    networks:
      - eureka
networks:
  eureka:
    driver: bridge