services:
  subscription_gateway:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
    build:
      context: ./subscription_gateway
    ports:
      - 8000
    networks:
      - eureka
  discovery_service:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
    build:
      context: ./discovery_service
    ports:
      - 8001
    hostname: discoveryservice
    networks:
      - eureka
  subscription_status_cache:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
    build:
      context: ./subscription_status_cache
    ports:
      - 8002
    networks:
      - eureka
  subscription_service:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
    build:
      context: ./subscription_service
    ports:
      - 8003
    networks:
      - eureka
networks:
  eureka:
    driver: bridge