services:
  subscription_gateway:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
    build:
      context: ./subscription_gateway
    ports:
      - 8080:8000
    networks:
      - eureka
    depends_on:
      - discovery_service
  discovery_service:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
    build:
      context: ./discovery_service
    ports:
      - 8001
    hostname: discoveryservice
    networks:
      - eureka
  subscription_status_cache:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=://kafka:9092
    build:
      context: ./subscription_status_cache
    ports:
      - 8002
    networks:
      - eureka
      - kafka
    deploy:
      replicas: 3
    depends_on:
      - discovery_service
      - kafka
      - subscription_service
  subscription_service:
    environment:
      - EUREKA_SERVICE_URL=http://discoveryservice:8001/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=://kafka:9092
    build:
      context: ./subscription_service
    ports:
      - 8003
    networks:
      - eureka
      - kafka
    depends_on:
      - discovery_service
      - kafka
  kafka:
    environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    ports:
      - 29092:29092
    image: confluentinc/cp-kafka:7.6.1
    hostname: kafka
    networks:
      - kafka
      - zookeeper
    depends_on:
      - zookeeper
  zookeeper:
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ADVERTISED_HOST_NAME=zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    ports:
      - 2181
    networks:
      - zookeeper
networks:
  eureka:
    driver: bridge
  kafka:
    driver: bridge
  zookeeper:
    driver: bridge