###
GET http://localhost:8080/servcad/clientes

<> 2024-04-27T141326.200.json
<> 2024-04-27T140237.200.json

###
GET http://localhost:8080/servcad/aplicativos

<> 2024-04-27T141330.200.json
<> 2024-04-27T140326.200.json
<> 2024-04-27T140247.200.json

###
POST http://localhost:8080/servcad/assinaturas
Content-Type: application/json

{
  "codigoCliente": 1,
  "codigoAplicativo": 1
}

<> 2024-04-27T141354.500.json
<> 2024-04-27T141340.500.json

###
POST http://localhost:8080/servcad/aplicativos/atualizacusto/{{applicationId}}
Content-Type: application/json

{
  "custo": 10
}

<> 2024-04-27T141336.200.json

###
GET http://localhost:8080/servcad/assinaturas

<> 2024-04-27T141416.200.json

###
GET http://localhost:8080/servcad/assinaturas/ATIVAS

###
GET http://localhost:8080/servcad/assinaturas/CANCELADAS

###
GET http://localhost:8080/servcad/assinaturas/TODAS

###
GET http://localhost:8080/servcad/asscli/1

###
GET http://localhost:8080/servcad/asscli/2

###
GET http://localhost:8080/servcad/asscli/3

###
@applicationId = 4
GET http://localhost:8080/servcad/assapp/{{applicationId}}

<> 2024-04-27T141334.200.json
<> 2024-04-27T141332.200.json
<> 2024-04-27T140518.200.json
<> 2024-04-27T140338.500.json

###
@valorInsuficiente = 10.5
POST http://localhost:8080/registrarpagamento
Content-Type: application/json

{
  "dia": 10,
  "mes": 2,
  "ano": 2024,
  "codass": 1,
  "valorPago": {{valorInsuficiente}}
}

###
@valorExcedente = 9999
POST http://localhost:8080/registrarpagamento
Content-Type: application/json

{
  "dia": 10,
  "mes": 2,
  "ano": 2024,
  "codass": 1,
  "valorPago": {{valorExcedente}}
}

###
@valorInvalido = -1
POST http://localhost:8080/registrarpagamento
Content-Type: application/json

{
  "dia": 10,
  "mes": 2,
  "ano": 2024,
  "codass": 1,
  "valorPago": {{valorInvalido}}
}


<> 2024-04-27T140954.500.json

###
@valorValido = 16.5
POST http://localhost:8080/registrarpagamento
Content-Type: application/json

{
  "dia": 10,
  "mes": 2,
  "ano": 2024,
  "codass": 1,
  "valorPago": {{valorValido}}
}

###
@assinaturaInvalida = 1
GET http://localhost:8080/assinvalida/{{assinaturaInvalida}}

###
@assinaturaValida = 4
GET http://localhost:8080/assinvalida/{{assinaturaValida}}
